import wallet from './wallet.module.scss'
import homeRight from "../HomeRight/homeright.module.scss";
import HomeBalance from "../HomeRight/Balance/homebalance";
import WatchList from "../HomeRight/WatchList/watchlist";
import BuyAndSellWidget from "../HomeRight/BuyAndSellWidget/buyandsellwidget";
import LatestActivities from "../HomeRight/LatestActivities/latestactivities";
import Head from "next/head";
import homeBalance from "../HomeRight/Balance/homebalance.module.scss";



export default function WalletContainer() {
    return (

        <div className={homeRight.page}>

            <div className={homeRight}>
                <Head>
                    <title>Privpay</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <div className={homeRight.rightGrid}>
                    <div className={homeRight.grey}>


                        <div className={homeRight.userProfile}>

                            <div className={homeRight.userProfileIcon}>
                                <img className={homeRight.userProfileIconImage} src='https://avatars.githubusercontent.com/u/2838987?v=4' width={30}  />

                            </div>

                            <div className={homeRight.userProfileName}>
                                <h4 className={homeRight.fullName}>
                                    Ade Tiger
                                </h4>
                                <p className={homeRight.email}>
                                    Adetiger@gmail.com
                                </p>


                            </div>


                        </div>

                    </div>




                    <div className={homeRight.lightGrey}>

<div className={wallet.container}>
<div className={wallet.balanceContainer}>
<h3 className={wallet.header}>Wallet</h3>

    <div className={homeBalance.container}>

        <div className={homeBalance.containerElement}>








            <div className={wallet.IconandText}>
                <div className={homeBalance.welcomeIcon}>
                    <img className={homeBalance.welcomeIconImage} src="data:image/svg+xml,%3Csvg width='34' height='34' viewBox='0 0 34 34' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath opacity='0.4' d='M17 31.0247C24.824 31.0247 31.1667 24.6821 31.1667 16.8581C31.1667 9.03404 24.824 2.69141 17 2.69141C9.17596 2.69141 2.83333 9.03404 2.83333 16.8581C2.83333 24.6821 9.17596 31.0247 17 31.0247Z' fill='%23D4B418'/%3E%3Cpath d='M20.2017 17L18.0626 16.2492V11.4467H18.5726C19.7201 11.4467 20.6551 12.4525 20.6551 13.685C20.6551 14.2658 21.1367 14.7475 21.7176 14.7475C22.2984 14.7475 22.7801 14.2658 22.7801 13.685C22.7801 11.2767 20.8959 9.32167 18.5726 9.32167H18.0626V8.5C18.0626 7.91917 17.5809 7.4375 17.0001 7.4375C16.4192 7.4375 15.9376 7.91917 15.9376 8.5V9.32167H15.0167C12.9201 9.32167 11.2059 11.0925 11.2059 13.26C11.2059 15.7958 12.6792 16.6033 13.7984 17L15.9376 17.7508V22.5392H15.4276C14.2801 22.5392 13.3451 21.5333 13.3451 20.3008C13.3451 19.72 12.8634 19.2383 12.2826 19.2383C11.7017 19.2383 11.2201 19.72 11.2201 20.3008C11.2201 22.7092 13.1042 24.6642 15.4276 24.6642H15.9376V25.5C15.9376 26.0808 16.4192 26.5625 17.0001 26.5625C17.5809 26.5625 18.0626 26.0808 18.0626 25.5V24.6783H18.9834C21.0801 24.6783 22.7942 22.9075 22.7942 20.74C22.7801 18.19 21.3067 17.3825 20.2017 17ZM14.5067 15.0025C13.7842 14.7475 13.3451 14.5067 13.3451 13.2742C13.3451 12.2683 14.0959 11.4608 15.0309 11.4608H15.9517V15.5125L14.5067 15.0025ZM18.9834 22.5533H18.0626V18.5017L19.4934 18.9975C20.2159 19.2525 20.6551 19.4933 20.6551 20.7258C20.6551 21.7317 19.9042 22.5533 18.9834 22.5533Z' fill='%23D4B418'/%3E%3C/svg%3E%0A" width={30} height={30}/>
                </div>
                <div className={homeBalance.welcomeDetails}>
                    <h4 className={homeBalance.welcomeBack}>
           <span className={homeBalance.usdBalance}>  $300.00                  <img className={homeBalance.eyeIcon}src="data:image/svg+xml,%3Csvg width='20' height='20' viewBox='0 0 20 20' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath opacity='0.4' d='M12.9833 9.99994C12.9833 11.6499 11.65 12.9833 10 12.9833C8.35001 12.9833 7.01668 11.6499 7.01668 9.99994C7.01668 8.34993 8.35001 7.0166 10 7.0166C11.65 7.0166 12.9833 8.34993 12.9833 9.99994Z' stroke='%23292D32' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'/%3E%3Cpath d='M9.99995 16.8918C12.9416 16.8918 15.6833 15.1584 17.5916 12.1584C18.3416 10.9834 18.3416 9.00843 17.5916 7.83343C15.6833 4.83343 12.9416 3.1001 9.99995 3.1001C7.05828 3.1001 4.31661 4.83343 2.40828 7.83343C1.65828 9.00843 1.65828 10.9834 2.40828 12.1584C4.31661 15.1584 7.05828 16.8918 9.99995 16.8918Z' stroke='%23292D32' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E%0A"  width={30} height={12}/>
 </span>
                    </h4>
                    <p className={homeBalance.myBalance}>
                        My Balance

                    </p>


                </div>

            </div>

            <img className={wallet.divider} src="data:image/svg+xml,%3Csvg width='2' height='142' viewBox='0 0 2 142' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 1V141' stroke='%23C4C4C4' stroke-width='0.8' stroke-linecap='square'/%3E%3C/svg%3E%0A"/>







        </div>

    </div>
</div>
</div>






                    </div>


                </div>
            </div>
        </div>
    )
}









