// import wallet from './wallet.module.scss'
import wallet from "../Wallet/wallet.module.scss";
import homeRight from "../HomeRight/homeright.module.scss";
import exchange from  "../Exchange/exchange.module.scss"
import Head from "next/head";
import Link from 'next/link'
import homeBalance from "../HomeRight/Balance/homebalance.module.scss";


import { DatePicker, message, Alert } from 'antd';

import * as React from 'react';
import Box from '@mui/material/Box';
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import FormControl from '@mui/material/FormControl';
import Select from '@mui/material/Select';
import settings from "../Settings/settings.module.scss";

import changepassword from  "./changepassword.module.scss"
export default function ChangePassword() {

    return (

        <div className={homeRight.page}>

            <div className={homeRight}>
                <Head>
                    <title>Privpay</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <div className={homeRight.rightGrid}>
                    <div className={homeRight.grey}>


                        <div className={homeRight.userProfile}>

                            <div className={homeRight.userProfileIcon}>
                                <img className={homeRight.userProfileIconImage} src='https://avatars.githubusercontent.com/u/2838987?v=4' width={30}  />

                            </div>

                            <div className={homeRight.userProfileName}>
                                <h4 className={homeRight.fullName}>
                                    Ade Tiger
                                </h4>
                                <p className={homeRight.email}>
                                    Adetiger@gmail.com
                                </p>


                            </div>


                        </div>

                    </div>




                    <div className={homeRight.lightGrey}>

                        <div className={exchange.container}>
                            <div className={exchange.exchangeContainer}>
                                <h3 className={exchange.header}>Change Password</h3>


                                <div className={changepassword.container}>
                                    <div className={changepassword.padding}>
                                    <form className={settings.profileFormElements}>

                                        <label htmlFor="fname"  className={changepassword.label}>Old Password</label>
                                        <input type="text" id="fname" name="fname" className={changepassword.oldpassword} placeholder="Enter your Old Password" />

                                        <div className={changepassword.formDiv}>
                                            <label htmlFor="lname" className={changepassword.label} >New Password</label>
                                            <br/>
                                            <input type="text" id="lname" name="lname" placeholder="Enter your New Password" className={changepassword.newpassword} />
                                        </div>

                                        <div className={changepassword.formDiv}>
                                            <label htmlFor="lname"  className={changepassword.label}>Confirm New Password</label>
                                            <br/>
                                            <input type="text" id="lname" name="lname" placeholder="Confirm your New Password" className={changepassword.newpassword} />

                                        </div>



                                        <button className={changepassword.changepassword}>
                                            Change Password
                                        </button>




                                    </form>
                                    </div>
                                </div>



                            </div>



                        </div>






                    </div>


                </div>
            </div>


        </div>


    )
}









