import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'
import navstyles from './navbar.module.scss'
import {logo,dashboardicon} from './icon'
import {useState} from "react";
import Modal from "./logoutmodal";

export default function NavBar( ) {
    const [showModal, setShowModal] = useState(false);
    return (

        <div className={navstyles.nav}>

            <div className={styles}>
                <Head>
                    <title>Privpay</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>


                <div className={navstyles.NavbarContainer}>

                    <div className={navstyles.NavBarContent}>
                        <Link href="/">
                            <img className={navstyles.logo} src="https://res.cloudinary.com/seunsanyaa/image/upload/v1638732233/svgg_1_yyzpku.png" width={200} height={25} />
                        </Link>

                        <div className={navstyles.menu}>
                            <div className={navstyles.IconandText}>
                           <h4 className={navstyles.h4}>  Menu</h4>
                            </div>
                            <div className={navstyles.menuLinks}>



                                <div className={navstyles.IconandText}>

                            <img className={navstyles.icon} src="data:image/svg+xml,%3Csvg  viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M7.24 2H5.34C3.15 2 2 3.15 2 5.33V7.23C2 9.41 3.15 10.56 5.33 10.56H7.23C9.41 10.56 10.56 9.41 10.56 7.23V5.33C10.57 3.15 9.42 2 7.24 2Z' fill='%23D4B418'/%3E%3Cpath opacity='0.4' d='M18.6699 2H16.7699C14.5899 2 13.4399 3.15 13.4399 5.33V7.23C13.4399 9.41 14.5899 10.56 16.7699 10.56H18.6699C20.8499 10.56 21.9999 9.41 21.9999 7.23V5.33C21.9999 3.15 20.8499 2 18.6699 2Z' fill='%23D4B418'/%3E%3Cpath d='M18.6699 13.4302H16.7699C14.5899 13.4302 13.4399 14.5802 13.4399 16.7602V18.6602C13.4399 20.8402 14.5899 21.9902 16.7699 21.9902H18.6699C20.8499 21.9902 21.9999 20.8402 21.9999 18.6602V16.7602C21.9999 14.5802 20.8499 13.4302 18.6699 13.4302Z' fill='%23292D32'/%3E%3Cpath opacity='0.4' d='M7.24 13.4302H5.34C3.15 13.4302 2 14.5802 2 16.7602V18.6602C2 20.8502 3.15 22.0002 5.33 22.0002H7.23C9.41 22.0002 10.56 20.8502 10.56 18.6702V16.7702C10.57 14.5802 9.42 13.4302 7.24 13.4302Z' fill='%23D4B418'/%3E%3C/svg%3E%0A" width={20} height={30}/>


                                    <Link href="/" >

                                        <a className={navstyles.menuLinkContent} >  Dashboard  </a>


                                    </Link>


                                </div>









                                <div className={navstyles.IconandText}>

                            <img className={navstyles.icon} src="data:image/svg+xml,%3Csvg width='24' height='24' viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath opacity='0.4' d='M22 12V17C22 20 20 22 17 22H7C4 22 2 20 2 17V12C2 9.28 3.64 7.38 6.19 7.06C6.45 7.02 6.72 7 7 7H17C17.26 7 17.51 7.00999 17.75 7.04999C20.33 7.34999 22 9.26 22 12Z' fill='%23D4B418'/%3E%3Cpath d='M17.7499 7.05C17.5099 7.01 17.2599 7.00001 16.9999 7.00001H6.99994C6.71994 7.00001 6.44994 7.02001 6.18994 7.06001C6.32994 6.78001 6.52994 6.52001 6.76994 6.28001L10.0199 3.02C11.3899 1.66 13.6099 1.66 14.9799 3.02L16.7299 4.79002C17.3699 5.42002 17.7099 6.22 17.7499 7.05Z' fill='%23292D32'/%3E%3Cpath d='M22 12.5H19C17.9 12.5 17 13.4 17 14.5C17 15.6 17.9 16.5 19 16.5H22' fill='%23292D32'/%3E%3C/svg%3E%0A" width={20} height={30}/>




                                    <Link href="/wallet" >

                                        <a className={navstyles.menuLinkContent} >  Wallet  </a>


                                    </Link>


                                </div>





                                <div className={navstyles.IconandText}>

                            <img className={navstyles.icon} src="data:image/svg+xml,%3Csvg width='24' height='24' viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M18.5 12.6499V16.3499C18.5 19.4699 15.59 21.9999 12 21.9999C8.41 21.9999 5.5 19.4699 5.5 16.3499V12.6499C5.5 15.7699 8.41 17.9999 12 17.9999C15.59 17.9999 18.5 15.7699 18.5 12.6499Z' fill='%23292D32'/%3E%3Cpath opacity='0.4' d='M18.5 7.6499V12.6499C18.5 15.7699 15.59 17.9999 12 17.9999C8.41 17.9999 5.5 15.7699 5.5 12.6499V7.6499C5.5 8.5599 5.75 9.3999 6.19 10.1199C7.26 11.8799 9.46 12.9999 12 12.9999C14.54 12.9999 16.74 11.8799 17.81 10.1199C18.25 9.3999 18.5 8.5599 18.5 7.6499Z' fill='%23D4B418'/%3E%3Cpath d='M18.5 7.65C18.5 8.56 18.25 9.4 17.81 10.12C16.74 11.88 14.54 13 12 13C9.46 13 7.26 11.88 6.19 10.12C5.75 9.4 5.5 8.56 5.5 7.65C5.5 4.53 8.41 2 12 2C13.8 2 15.42 2.63 16.6 3.65C17.77 4.68 18.5 6.09 18.5 7.65Z' fill='%23D4B418'/%3E%3C/svg%3E%0A" width={20} height={30}/>




                                    <Link href="/activities">

                                        <a className={navstyles.menuLinkContent}> Activities  </a>


                                    </Link>


                                </div>






                                <div className={navstyles.IconandText}>

                            <img className={navstyles.icon} src="data:image/svg+xml,%3Csvg width='24' height='24' viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath opacity='0.4' d='M7.81 2H16.18C19.83 2 22 4.17 22 7.81V16.18C22 19.82 19.83 21.99 16.19 21.99H7.81C4.17 22 2 19.83 2 16.19V7.81C2 4.17 4.17 2 7.81 2Z' fill='%23D4B418'/%3E%3Cpath d='M10.24 6.25C9.81998 6.25 9.48998 6.59 9.48998 7V15.19L7.81998 13.52C7.52998 13.23 7.04998 13.23 6.75998 13.52C6.46998 13.81 6.46998 14.29 6.75998 14.58L9.70998 17.53C9.77998 17.6 9.85998 17.65 9.94998 17.69C10.04 17.73 10.14 17.75 10.24 17.75C10.34 17.75 10.43 17.73 10.53 17.69C10.71 17.61 10.86 17.47 10.94 17.28C10.98 17.19 11 17.09 11 16.99V7C10.99 6.59 10.65 6.25 10.24 6.25Z' fill='%23292D32'/%3E%3Cpath d='M17.24 9.42L14.29 6.47C14.22 6.4 14.14 6.35 14.05 6.31C13.87 6.23 13.66 6.23 13.48 6.31C13.3 6.39 13.15 6.53 13.07 6.72C13.03 6.81 13.01 6.9 13.01 7V17C13.01 17.41 13.35 17.75 13.76 17.75C14.17 17.75 14.51 17.41 14.51 17V8.81L16.18 10.48C16.33 10.63 16.52 10.7 16.71 10.7C16.9 10.7 17.09 10.63 17.24 10.48C17.53 10.19 17.53 9.71 17.24 9.42Z' fill='%23292D32'/%3E%3C/svg%3E%0A" width={20} height={30}/>




                                    <Link href="/exchange" >

                                        <a className={navstyles.menuLinkContent}> Exchange  </a>


                                    </Link>


                                </div>










                            </div>


                        </div>


                        <img  className={navstyles.divider} src="data:image/svg+xml,%3Csvg width='348' height='2' viewBox='0 0 348 2' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M0 1H348' stroke='%23C4C4C4' stroke-opacity='0.54'/%3E%3C/svg%3E%0A" />

                        <div className={navstyles.others}>
                           <h4 className={navstyles.h4}>Others</h4>
                            <div className={navstyles.othersLink}>

                                <div className={navstyles.IconandText}>

                            <img className={navstyles.icon}  src="data:image/svg+xml,%3Csvg width='24' height='24' viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath opacity='0.4' d='M2 12.8799V11.1199C2 10.0799 2.85 9.21994 3.9 9.21994C5.71 9.21994 6.45 7.93994 5.54 6.36994C5.02 5.46994 5.33 4.29994 6.24 3.77994L7.97 2.78994C8.76 2.31994 9.78 2.59994 10.25 3.38994L10.36 3.57994C11.26 5.14994 12.74 5.14994 13.65 3.57994L13.76 3.38994C14.23 2.59994 15.25 2.31994 16.04 2.78994L17.77 3.77994C18.68 4.29994 18.99 5.46994 18.47 6.36994C17.56 7.93994 18.3 9.21994 20.11 9.21994C21.15 9.21994 22.01 10.0699 22.01 11.1199V12.8799C22.01 13.9199 21.16 14.7799 20.11 14.7799C18.3 14.7799 17.56 16.0599 18.47 17.6299C18.99 18.5399 18.68 19.6999 17.77 20.2199L16.04 21.2099C15.25 21.6799 14.23 21.3999 13.76 20.6099L13.65 20.4199C12.75 18.8499 11.27 18.8499 10.36 20.4199L10.25 20.6099C9.78 21.3999 8.76 21.6799 7.97 21.2099L6.24 20.2199C5.33 19.6999 5.02 18.5299 5.54 17.6299C6.45 16.0599 5.71 14.7799 3.9 14.7799C2.85 14.7799 2 13.9199 2 12.8799Z' fill='%23D4B418'/%3E%3Cpath d='M12 15.25C13.7949 15.25 15.25 13.7949 15.25 12C15.25 10.2051 13.7949 8.75 12 8.75C10.2051 8.75 8.75 10.2051 8.75 12C8.75 13.7949 10.2051 15.25 12 15.25Z' fill='%23292D32'/%3E%3C/svg%3E%0A" width={20} height={30}/>


                                    <Link href="/settings" >

                                        <a className={navstyles.menuLinkContent}>  Settings </a>


                                    </Link>


                                </div>
                                <div className={navstyles.IconandText}>

                            <img className={navstyles.icon}  src="data:image/svg+xml,%3Csvg width='24' height='24' viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath opacity='0.4' d='M9 7.2V16.79C9 20 11 22 14.2 22H16.79C19.99 22 21.99 20 21.99 16.8V7.2C22 4 20 2 16.8 2H14.2C11 2 9 4 9 7.2Z' fill='%23D4B418'/%3E%3Cpath d='M5.56994 8.12002L2.21994 11.47C1.92994 11.76 1.92994 12.24 2.21994 12.53L5.56994 15.88C5.85994 16.17 6.33994 16.17 6.62994 15.88C6.91994 15.59 6.91994 15.11 6.62994 14.82L4.55994 12.75H15.2499C15.6599 12.75 15.9999 12.41 15.9999 12C15.9999 11.59 15.6599 11.25 15.2499 11.25H4.55994L6.62994 9.18002C6.77994 9.03002 6.84994 8.84002 6.84994 8.65002C6.84994 8.46002 6.77994 8.26002 6.62994 8.12002C6.33994 7.82002 5.86994 7.82002 5.56994 8.12002Z' fill='%23292D32'/%3E%3C/svg%3E%0A" width={20} height={30}/>





                                        <button onClick={() => setShowModal(true)} className={navstyles.logout}>Logout</button>
                                        <Modal
                                            onClose={() => setShowModal(false)}
                                            show={showModal}
                                        >
                                          <div className={navstyles.logoutModal}>

                                              <img className={navstyles.icon}  src="data:image/svg+xml,%3Csvg width='24' height='24' viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath opacity='0.4' d='M9 7.2V16.79C9 20 11 22 14.2 22H16.79C19.99 22 21.99 20 21.99 16.8V7.2C22 4 20 2 16.8 2H14.2C11 2 9 4 9 7.2Z' fill='%23D4B418'/%3E%3Cpath d='M5.56994 8.12002L2.21994 11.47C1.92994 11.76 1.92994 12.24 2.21994 12.53L5.56994 15.88C5.85994 16.17 6.33994 16.17 6.62994 15.88C6.91994 15.59 6.91994 15.11 6.62994 14.82L4.55994 12.75H15.2499C15.6599 12.75 15.9999 12.41 15.9999 12C15.9999 11.59 15.6599 11.25 15.2499 11.25H4.55994L6.62994 9.18002C6.77994 9.03002 6.84994 8.84002 6.84994 8.65002C6.84994 8.46002 6.77994 8.26002 6.62994 8.12002C6.33994 7.82002 5.86994 7.82002 5.56994 8.12002Z' fill='%23292D32'/%3E%3C/svg%3E%0A" width={30} height={30}/>
<h4 className={navstyles.logoutParagraph}>Are you sure you want to log out?</h4>

                                              <div className={navstyles.yesOrno}>
                                                  <Link href="/logout" >

                                                      <button className={navstyles.yes}>
Yes
                                                      </button>


                                                  </Link>

<button className={navstyles.no} onClick={() => setShowModal(false)}>
                                                      No
                                                  </button>


                                              </div>
                                          </div>
                                        </Modal>



                                </div>
                            </div>

                        </div>

                    </div>


                </div>
            </div>
        </div>
    )
}
