import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'
import homeRight from './homeright.module.scss'
import {logo,dashboardicon} from './icon'
export default function HomeRight() {
    return (

        <div className={homeRight.page}>

            <div className={homeRight}>
                <Head>
                    <title>Privpay</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

<div className={homeRight.rightGrid}>
    <div className={homeRight.grey}>




    </div>

    <div className={homeRight.lightGrey}>




    </div>



</div>
            </div>
        </div>
    )
}
