// import wallet from './wallet.module.scss'
import wallet from "../Wallet/wallet.module.scss";
import homeRight from "../HomeRight/homeright.module.scss";
import exchange from  "../Exchange/exchange.module.scss"
import Head from "next/head";
import Link from 'next/link'
import homeBalance from "../HomeRight/Balance/homebalance.module.scss";




export default function ExchangeContainer() {
    return (

        <div className={homeRight.page}>

            <div className={homeRight}>
                <Head>
                    <title>Privpay</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <div className={homeRight.rightGrid}>
                    <div className={homeRight.grey}>


                        <div className={homeRight.userProfile}>

                            <div className={homeRight.userProfileIcon}>
                                <img className={homeRight.userProfileIconImage} src='https://avatars.githubusercontent.com/u/2838987?v=4' width={30}  />

                            </div>

                            <div className={homeRight.userProfileName}>
                                <h4 className={homeRight.fullName}>
                                    Ade Tiger
                                </h4>
                                <p className={homeRight.email}>
                                    Adetiger@gmail.com
                                </p>


                            </div>


                        </div>

                    </div>




                    <div className={homeRight.lightGrey}>

                        <div className={exchange.container}>
                            <div className={exchange.exchangeContainer}>
                                <h3 className={exchange.header}>Wallet</h3>


                                <div className={homeBalance.container}>

                                    <div className={exchange.containerElement}>



<div className={exchange.grid}>


    <div className={exchange.left}>
        <h4>From</h4>

        <form className={exchange.leftForm}>

        <select>
<option>   BTC</option>

        </select>


        <input placeholder="4999.98767777"/>

        </form>

    </div>

    {/*<div className={wallet.buttonDiv}>*/}
    {/*    <button className={wallet.button}> <img src="data:image/svg+xml,%3Csvg width='21' height='21' viewBox='0 0 21 21' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath opacity='0.4' d='M6.83756 2.1748H13.6828C16.6679 2.1748 18.4426 3.94951 18.4426 6.92642V13.7717C18.4426 16.7486 16.6679 18.5233 13.691 18.5233H6.83756C3.86064 18.5315 2.08594 16.7568 2.08594 13.7799V6.92642C2.08594 3.94951 3.86064 2.1748 6.83756 2.1748Z' fill='%23D4B418'/%3E%3Cpath d='M14.9178 11.5631C14.8524 11.4159 14.7379 11.2932 14.5825 11.2278C14.5089 11.1951 14.4271 11.1787 14.3453 11.1787H6.17514C5.83983 11.1787 5.56177 11.4568 5.56177 11.7921C5.56177 12.1274 5.83983 12.4055 6.17514 12.4055H12.8732L11.5074 13.7712C11.2703 14.0084 11.2703 14.401 11.5074 14.6381C11.6301 14.7608 11.7855 14.8181 11.9409 14.8181C12.0963 14.8181 12.2517 14.7608 12.3743 14.6381L14.7869 12.2255C14.8442 12.1683 14.8851 12.1029 14.9178 12.0293C14.9832 11.8739 14.9832 11.7103 14.9178 11.5631Z' fill='%23292D32'/%3E%3Cpath d='M5.61084 9.14258C5.67626 9.28979 5.79076 9.41247 5.94615 9.4779C6.01975 9.51061 6.09336 9.52697 6.17514 9.52697H14.3535C14.6888 9.52697 14.9669 9.2489 14.9669 8.91359C14.9669 8.57828 14.6888 8.30021 14.3535 8.30021H7.65542L9.02121 6.93443C9.25838 6.69726 9.25838 6.3047 9.02121 6.06753C8.78403 5.83036 8.39147 5.83036 8.1543 6.06753L5.74169 8.48014C5.68444 8.53739 5.64355 8.60281 5.61084 8.67642C5.54541 8.83181 5.54541 8.99537 5.61084 9.14258Z' fill='%23292D32'/%3E%3C/svg%3E%0A"/>*/}
    {/*        <span className={wallet.span}>Pay</span></button>*/}


    {/*</div>*/}


</div>








                                    </div>

                                </div>



                            </div>



                        </div>






                    </div>


                </div>
            </div>
        </div>
    )
}









